(load "~/.emacs.d/personal/keybindings.el")
(load "~/.emacs.d/personal/python.el")
(load "~/.emacs.d/personal/javascript.el")
(load "~/.emacs.d/personal/ruby.el")
(load "~/.emacs.d/personal/powerline.el")
(load "~/.emacs.d/personal/global.el")
